# Generated by Django 5.1.2 on 2025-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=200, null=True)),
                ('Pro_price', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
